### ISSUE TITLE
Document expected Node version

### ISSUE THREAD

**Issue by ramblingenzyme** [Atlas-Authority/marketing-automation#40]
* We're currently tackling upgrading the Node version we use internally.
* Project doesn't work on 12, and requires a ts-node upgrade to work with 16. Can I assume it's being developed against Node 14 then?
* Could we add a .nvmrc file to track what the expected version is?
* Using nvm Node 14 ships with npm 6 which isn't compatible with the v2 package-lock.json file and rewrites it
* Node 16 ships npm 8 which is compatible with the package-lock.json, so that confuses the issue again.

**Comment by sdegutis** [comment]
It's currently being developed against Node 16 actually, but I'm not sure there's anything _specific_ to Node 16 that we need. We might be able to use Node 14 or possibly 12.

The biggest thing is ESM support, which we mostly only have currently because the dice coefficient package is ESM only. But that's MIT and 2 small files, so would be reasonable to pull into this repo to load with CJS if need be. (And of course wrap top-level async in bin-scripts with async function but that's not an issue, just a task.)

**Comment by sdegutis** [comment]
Do any consumers of this framework have any requests for specific versions of Node or NPM? We currently use Node 16 and NPM 7/8, mainly for ESM support and package-lock v2 format (i.e. improved NPM speed).

**Comment by ramblingenzyme** [comment]
No opinion on the versions, just care about having it documented + a .nvmrc file so people don't have to figure it out.

**Comment by sdegutis** [comment]
Added .nvmrc and updated readme.
